05_django/03_model/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create')
]

05_django/03_model/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

05_django/03_model/articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def new(request):
    return render(request, 'articles/new.html')

def create(request):

    print('='*30)
    print(request.GET)
    print('='*30)

    title = request.GET.get('title')
    content = request.GET.get('content')
    print(title, content)

    # ORM
    # class.manager.queryAPI
    # Article.object.create()

    # 3가지 방법이 있다.
    # 1. article instance 생성하는 방법
    article = Article()
    return render(request, 'articles/create.html')

05_django/03_model/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글이 생성 되었습니다.</h1>
  <a href="{% url 'articles:index' %}">[메인 페이지로]</a>
{% endblock content %}

05_django/03_model/articles/templates/articles/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>INDEX PAGE</h1>

  <a href="{% url 'articles:new' %}">new로 이동</a>
{% endblock content %}

05_django/03_model/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글 생성 페이지</h1>
  <form action="{% url 'articles:create' %}">
    <label for="title">제목 : </label>
    <input type="text" name="title" id="title">

    <label for="content">내용</label>
    <input type="text" name="content" id="content">

    <input type="submit">
    <br>
    <a href="{% url 'articles:index' %}">INDEX로 이동</a>
  </form>
{% endblock content %}